
const __sby_p = (() => {
  const a = [77,111,98,105,110,98,105,98,97,107];
  return Object.freeze({
    id: a.map((n,i) => String.fromCharCode(n ^ 0)).join(''),
    stamp: 'subify-provenance-v2416'
  });
})();
const $=id=>document.getElementById(id);let scenes=[];let dbp=null;function db(){if(dbp)return dbp;dbp=new Promise((res,rej)=>{const r=indexedDB.open("subify-local",2);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains("storyboards"))d.createObjectStore("storyboards");if(!d.objectStoreNames.contains("translations"))d.createObjectStore("translations");if(!d.objectStoreNames.contains("vocab"))d.createObjectStore("vocab");if(!d.objectStoreNames.contains("shots"))d.createObjectStore("shots")};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});return dbp}async function get(){const d=await db();return new Promise(r=>{const q=d.transaction("storyboards","readonly").objectStore("storyboards").get("current");q.onsuccess=()=>r(q.result||[])});}async function put(v){const d=await db();return new Promise((r,j)=>{const q=d.transaction("storyboards","readwrite").objectStore("storyboards").put(v,"current");q.onsuccess=()=>r();q.onerror=()=>j(q.error)})}async function tab(){const [t]=await chrome.tabs.query({active:true,currentWindow:true});return t}function time(x){x=Number(x)||0;const m=Math.floor(x/60),s=Math.floor(x%60);return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;}function esc(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));}async function render(){scenes=await get();$("status").textContent=`${scenes.length} شات`;$("board").innerHTML=scenes.length?scenes.map((s,i)=>`<article class="scene">${s.image?`<img src="${s.image}" alt="">`:`<div style="aspect-ratio:16/9;background:#111"></div>`}<div class="body"><div class="time">#${i+1} • ${time(s.start)}</div><div class="orig">${esc(s.original||"")}</div><div class="fa">${esc(s.fa||"")}</div><div class="small">${esc(s.title||"")}</div></div></article>`).join(""):`<div class="empty" style="grid-column:1/-1">هنوز شاتی اضافه نشده.</div>`}
async function addCurrent(){const t=await tab();if(!t?.id)return;const cue=await chrome.tabs.sendMessage(t.id,{type:"subify-get-current-cue"}).catch(()=>null);const shot=await chrome.runtime.sendMessage({type:"subify-capture-shot",tabId:t.id,download:false}).catch(()=>null);if(!cue?.cue){$("status").textContent="در این لحظه زیرنویس فعالی پیدا نشد.";return;}scenes.push({id:crypto.randomUUID(),start:cue.cue.start,end:cue.cue.end,original:cue.cue.text,fa:cue.cue.fa,title:t.title||"",image:shot?.dataUrl||"",createdAt:Date.now()});await put(scenes);render();}
async function build(){const t=await tab();if(!t?.id)return;const r=await chrome.tabs.sendMessage(t.id,{type:"subify-refresh-captions",translateAll:false}).catch(()=>null);if(!r?.ok){$("status").textContent=r?.error||"زیرنویس در دسترس نیست";return;}scenes=(r.cues||[]).slice(0,120).map((c,i)=>({id:`cue-${i}-${c.id}`,start:c.start,end:c.end,original:c.text,fa:c.fa,title:t.title||"",image:"",createdAt:Date.now()}));await put(scenes);render();}$("addCurrent").onclick=addCurrent;$("build").onclick=build;$("clear").onclick=async()=>{scenes=[];await put([]);render()};$("export").onclick=()=>{const b=new Blob([JSON.stringify(scenes,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="subify-storyboard.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};render();
